import {
  LOCAL_WHISPER_FRAME_HEADER_BYTES,
  LOCAL_WHISPER_MAX_AUDIO_CHUNK_BYTES,
  LOCAL_WHISPER_MAX_CONTROL_FRAME_BYTES,
  LOCAL_WHISPER_MAX_REQUEST_ID_BYTES,
} from '@shared/localWhisper';

export const LOCAL_WHISPER_HANDSHAKE_TIMEOUT_MS = 10_000;
export const LOCAL_WHISPER_PROBE_TIMEOUT_MS = 30_000;
export const LOCAL_WHISPER_LOAD_TIMEOUT_MS = 5 * 60_000;
export const LOCAL_WHISPER_WARMUP_TIMEOUT_MS = 2 * 60_000;
export const LOCAL_WHISPER_UNLOAD_TIMEOUT_MS = 15_000;
export const LOCAL_WHISPER_TERMINATE_TIMEOUT_MS = 5_000;
export const LOCAL_WHISPER_KILL_CONFIRMATION_TIMEOUT_MS = 5_000;
export const LOCAL_WHISPER_MIN_TRANSCRIPTION_TIMEOUT_MS = 2 * 60_000;
export const LOCAL_WHISPER_MAX_TRANSCRIPTION_TIMEOUT_MS = 30 * 60_000;
export const LOCAL_WHISPER_TRANSCRIPTION_DURATION_MULTIPLIER = 10;
export const LOCAL_WHISPER_MAX_OUTGOING_QUEUE_BYTES = 2 * 1024 * 1024;
export const LOCAL_WHISPER_MAX_FRAMES_PER_CHUNK = 256;

export const LOCAL_WHISPER_MAX_AUDIO_BODY_BYTES =
  1 + 1 + 4 + 2 + LOCAL_WHISPER_MAX_REQUEST_ID_BYTES + LOCAL_WHISPER_MAX_AUDIO_CHUNK_BYTES;
export const LOCAL_WHISPER_MAX_FRAME_BYTES =
  LOCAL_WHISPER_FRAME_HEADER_BYTES +
  Math.max(LOCAL_WHISPER_MAX_CONTROL_FRAME_BYTES, LOCAL_WHISPER_MAX_AUDIO_BODY_BYTES);

export function getLocalWhisperTranscriptionTimeoutMs(audioDurationMs: number): number {
  if (!Number.isFinite(audioDurationMs) || audioDurationMs < 0) {
    throw new Error('Invalid Local Whisper audio duration');
  }
  return Math.ceil(
    Math.min(
      LOCAL_WHISPER_MAX_TRANSCRIPTION_TIMEOUT_MS,
      Math.max(
        LOCAL_WHISPER_MIN_TRANSCRIPTION_TIMEOUT_MS,
        audioDurationMs * LOCAL_WHISPER_TRANSCRIPTION_DURATION_MULTIPLIER,
      ),
    ),
  );
}
