function(local_whisper_configure_linux_libfuzzer sanitizer_option)
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "Local Whisper libFuzzer targets are supported on Linux only")
  endif()
  if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    message(FATAL_ERROR "Local Whisper libFuzzer targets require Clang")
  endif()
  if(NOT ${sanitizer_option})
    message(FATAL_ERROR "Local Whisper libFuzzer targets require non-recovering ASan and UBSan")
  endif()
endfunction()

function(local_whisper_add_linux_libfuzzer_target target sanitizer_option)
  local_whisper_configure_linux_libfuzzer(${sanitizer_option})
  local_whisper_apply_compile_hardening(${target} ${sanitizer_option})
  target_compile_options(${target} PRIVATE -fsanitize=fuzzer)
  target_link_options(${target} PRIVATE -fsanitize=fuzzer)
endfunction()
